/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package List;

import LSubProces.Delete;
import Master.*;

/**
 *
 * @author richky
 */
public class ListSubMaster extends javax.swing.JFrame {

    /**
     * Creates new form ListKaryawan
     */
    String Title;

    public ListSubMaster(String title) {
        Title = title;
        initComponents();
        setVisible(true);
        setTitle("List Sub Master " + Title);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        switch (Title) {
            case "Jenis Karyawan":
                refreshJenisKaryawan();
                break;
            case "Jenis Barang":
                refreshJenisBarang();
                break;
            case "Jenis Penjualan":
                refreshJenisPenjualan();
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonF1 = new KomponenGUI.JbuttonF();
        jbuttonF2 = new KomponenGUI.JbuttonF();
        jbuttonF3 = new KomponenGUI.JbuttonF();
        jbuttonF4 = new KomponenGUI.JbuttonF();
        jcomCari1 = new KomponenGUI.JcomCari();
        jbuttonF5 = new KomponenGUI.JbuttonF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbuttonF1.setText("Ubah");
        jbuttonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF1ActionPerformed(evt);
            }
        });

        jbuttonF2.setText("Hapus");
        jbuttonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF2ActionPerformed(evt);
            }
        });

        jbuttonF3.setText("Refresh");
        jbuttonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF3ActionPerformed(evt);
            }
        });

        jbuttonF4.setText("Kembali");
        jbuttonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF4ActionPerformed(evt);
            }
        });

        jbuttonF5.setText("Tambah");
        jbuttonF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuttonF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jcomCari1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcomCari1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF1ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                ubahJenisKaryawan();
                break;
            case "Jenis Barang":
                ubahJenisBarang();
                break;
            case "Jenis Penjualan":
                ubahJenisPenjualan();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF1ActionPerformed

    private void jbuttonF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF4ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                GlobalVar.Var.listJenisKaryawan.dispose();
                GlobalVar.Var.listJenisKaryawan = null;
                break;
            case "Jenis Barang":
                GlobalVar.Var.listJenisBarang.dispose();
                GlobalVar.Var.listJenisBarang = null;
                break;
            case "Jenis Penjualan":
                GlobalVar.Var.listJenisPenjualan.dispose();
                GlobalVar.Var.listJenisPenjualan = null;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        switch (Title) {
            case "Jenis Karyawan":
                GlobalVar.Var.listJenisKaryawan = null;
                break;
            case "Jenis Barang":
                GlobalVar.Var.listJenisBarang = null;
                break;
            case "Jenis Penjualan":
                GlobalVar.Var.listJenisPenjualan = null;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formWindowClosing

    private void jbuttonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF2ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                hapusJenisKaryawan();
                break;
            case "Jenis Barang":
                hapusJenisBarang();
                break;
            case "Jenis Penjualan":
                hapusJenisPenjualan();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF2ActionPerformed

    private void jbuttonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF3ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                refreshJenisKaryawan();
                break;
            case "Jenis Barang":
                refreshJenisBarang();
                break;
            case "Jenis Penjualan":
                refreshJenisPenjualan();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF3ActionPerformed

    private void jbuttonF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF5ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                tambahJenisKaryawan();
                break;
            case "Jenis Barang":
                tambahJenisBarang();
                break;
            case "Jenis Penjualan":
                tambahJenisPenjualan();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSubMaster("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private KomponenGUI.JbuttonF jbuttonF1;
    private KomponenGUI.JbuttonF jbuttonF2;
    private KomponenGUI.JbuttonF jbuttonF3;
    private KomponenGUI.JbuttonF jbuttonF4;
    private KomponenGUI.JbuttonF jbuttonF5;
    private KomponenGUI.JcomCari jcomCari1;
    // End of variables declaration//GEN-END:variables

    void tambahJenisKaryawan() {
        if (GlobalVar.Var.tambahJenisKaryawan == null){
            GlobalVar.Var.tambahJenisKaryawan = new SubMaster("Jenis Karyawan");
        }
    }
    
    void tambahJenisBarang() {
        if (GlobalVar.Var.tambahJenisBarang == null){
            GlobalVar.Var.tambahJenisBarang = new SubMaster("Jenis Barang");
        }
    }
    
    void tambahJenisPenjualan() {
        if (GlobalVar.Var.tambahJenisPenjualan == null){
            GlobalVar.Var.tambahJenisPenjualan = new SubMaster("Jenis Penjualan");
        }
    }
    
    void hapusJenisKaryawan() {
        if (jcomCari1.getSelectedRow() != -1) {
            Delete delete = new Delete();
            Boolean berhasil = delete.Hapus("ID " + jcomCari1.GetIDTable(), "DELETE FROM `tbsmjeniskaryawan` WHERE `IdJenisKaryawan` = " + jcomCari1.GetIDTable(), "Jenis Karyawan", this);
            if (berhasil) {
                refreshJenisKaryawan();
            }
        }
    }
    
    void hapusJenisBarang() {
        if (jcomCari1.getSelectedRow() != -1) {
            Delete delete = new Delete();
            Boolean berhasil = delete.Hapus("ID " + jcomCari1.GetIDTable(), "DELETE FROM `tbsmjenisbarang` WHERE `IdJenisBarang` = " + jcomCari1.GetIDTable(), "Jenis Barang", this);
            if (berhasil) {
                refreshJenisBarang();
            }
        }
    }
    
    void hapusJenisPenjualan() {
        if (jcomCari1.getSelectedRow() != -1) {
            Delete delete = new Delete();
            Boolean berhasil = delete.Hapus("ID " + jcomCari1.GetIDTable(), "DELETE FROM `tbsmjenispenjualan` WHERE `IdJenisPenjualan` = " + jcomCari1.GetIDTable(), "Jenis Penjualan", this);
            if (berhasil) {
                refreshJenisPenjualan();
            }
        }
    }

    void ubahJenisKaryawan() {
        if (jcomCari1.getSelectedRow() != -1 && GlobalVar.Var.ubahJenisKaryawan == null) {
            GlobalVar.Var.ubahJenisKaryawan = new SubMaster(jcomCari1.GetIDTable(), "Jenis Karyawan");
        }
    }
    
    void ubahJenisBarang() {
        if (jcomCari1.getSelectedRow() != -1 && GlobalVar.Var.ubahJenisBarang == null) {
            GlobalVar.Var.ubahJenisBarang = new SubMaster(jcomCari1.GetIDTable(), "Jenis Barang");
        }
    }
    
    void ubahJenisPenjualan() {
        if (jcomCari1.getSelectedRow() != -1 && GlobalVar.Var.ubahJenisPenjualan == null) {
            GlobalVar.Var.ubahJenisPenjualan = new SubMaster(jcomCari1.GetIDTable(), "Jenis Penjualan");
        }
    }

    public void refreshJenisKaryawan() {
        jcomCari1.setQuery("SELECT `IdJenisKaryawan` as 'ID', `JenisKaryawan` as 'Jenis', `Keterangan` FROM `tbsmjeniskaryawan` WHERE 1");
        jcomCari1.Tampilkan();
    }
    
    public void refreshJenisBarang() {
        jcomCari1.setQuery("SELECT `IdJenisBarang` as 'ID', `JenisBarang` as 'Jenis', `Keterangan` FROM `tbsmjenisbarang` WHERE 1");
        jcomCari1.Tampilkan();
    }
    
    public void refreshJenisPenjualan() {
        jcomCari1.setQuery("SELECT `IdJenisPenjualan` as 'ID', `JenisPenjualan` as 'Jenis', `Keterangan` FROM `tbsmjenispenjualan` WHERE 1");
        jcomCari1.Tampilkan();
    }

}
