/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import LSubProces.DRunSelctOne;
import LSubProces.Insert;
import LSubProces.Update;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author richky
 */
public class SubMaster extends javax.swing.JFrame {

    /**
     * Creates new form MasterKaryawan
     */
    String IdEdit, Title;

    public SubMaster(String title) {
        Title = title;
        initComponents();
        setVisible(true);
        setTitle("Sub Master " + Title);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jbuttonF3.setVisible(false);
        jlableF1.setText(Title);
    }

    public SubMaster(Object idEdit, String title) {
        IdEdit = idEdit.toString();
        Title = title;
        initComponents();
        setVisible(true);
        setTitle("Ubah Sub Master " + Title);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jbuttonF1.setVisible(false);
        jbuttonF2.setVisible(false);
        switch (Title) {
            case "Jenis Karyawan":
                loadeditdatajeniskaryawan();
                break;
            case "Jenis Barang":
                loadeditdatajenisbarang();
                break;
            case "Jenis Penjualan":
                loadeditdatajenispenjualan();
                break;
            default:
                break;
        }
        jlableF1.setText(Title);
    }

    void loadeditdatajeniskaryawan() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdJenisKaryawan` as 'ID', `JenisKaryawan` as 'Jenis', `Keterangan` FROM `tbsmjeniskaryawan` WHERE `IdJenisKaryawan` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        jtextF1.setText(list.get(1));
        jTextAreaF1.setText(list.get(2));
    }

    void loadeditdatajenisbarang() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdJenisBarang` as 'ID', `JenisBarang` as 'Jenis', `Keterangan` FROM `tbsmjenisbarang` WHERE `IdJenisBarang` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        jtextF1.setText(list.get(1));
        jTextAreaF1.setText(list.get(2));
    }

    void loadeditdatajenispenjualan() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdJenisPenjualan` as 'ID', `JenisPenjualan` as 'Jenis', `Keterangan` FROM `tbsmjenispenjualan` WHERE `IdJenisPenjualan` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        jtextF1.setText(list.get(1));
        jTextAreaF1.setText(list.get(2));
    }

    Boolean checkInput() {
        if (jtextF1.getText().replace(" ", "").equals("")) {
            JOptionPane.showMessageDialog(null, Title + " Tidak Boleh Kosong");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlableF1 = new KomponenGUI.JlableF();
        jlableF3 = new KomponenGUI.JlableF();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaF1 = new KomponenGUI.JTextAreaF();
        jtextF1 = new KomponenGUI.JtextF();
        jbuttonF1 = new KomponenGUI.JbuttonF();
        jbuttonF2 = new KomponenGUI.JbuttonF();
        jbuttonF4 = new KomponenGUI.JbuttonF();
        jlableF6 = new KomponenGUI.JlableF();
        jlableF8 = new KomponenGUI.JlableF();
        jbuttonF3 = new KomponenGUI.JbuttonF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jlableF1.setText("Nama Karyawan");

        jlableF3.setText("Keterangan");

        jTextAreaF1.setColumns(20);
        jTextAreaF1.setRows(5);
        jTextAreaF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaF1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaF1);

        jtextF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtextF1KeyPressed(evt);
            }
        });

        jbuttonF1.setText("Tambah");
        jbuttonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF1ActionPerformed(evt);
            }
        });

        jbuttonF2.setText("Tambah & Tutup");
        jbuttonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF2ActionPerformed(evt);
            }
        });

        jbuttonF4.setText("Kembali");
        jbuttonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF4ActionPerformed(evt);
            }
        });

        jlableF6.setText(":");

        jlableF8.setText(":");

        jbuttonF3.setText("Ubah");
        jbuttonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlableF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlableF3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlableF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextF1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlableF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF1ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                tambahDataJenisKaryawan(false);
                break;
            case "Jenis Barang":
                tambahDataJenisBarang(false);
                break;
            case "Jenis Penjualan":
                tambahDataJenisPenjualan(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF1ActionPerformed

    private void jbuttonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF2ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                tambahDataJenisKaryawan(true);
                break;
            case "Jenis Barang":
                tambahDataJenisBarang(true);
                break;
            case "Jenis Penjualan":
                tambahDataJenisPenjualan(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF2ActionPerformed

    private void jbuttonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF3ActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                ubahDataJenisKaryawan();
                break;
            case "Jenis Barang":
                ubahDataJenisBarang();
                break;
            case "Jenis Penjualan":
                ubahDataJenisPenjualan();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jbuttonF3ActionPerformed

    private void jbuttonF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF4ActionPerformed
        dispose();
    }//GEN-LAST:event_jbuttonF4ActionPerformed

    private void jtextF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextF1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextAreaF1.requestFocus();
        }
    }//GEN-LAST:event_jtextF1KeyPressed

    private void jTextAreaF1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaF1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (IdEdit == null) {
                switch (Title) {
                    case "Jenis Karyawan":
                        tambahDataJenisKaryawan(false);
                        break;
                    case "Jenis Barang":
                        tambahDataJenisBarang(false);
                        break;
                    case "Jenis Penjualan":
                        tambahDataJenisPenjualan(false);
                        break;
                    default:
                        break;
                }
            } else {
                switch (Title) {
                    case "Jenis Karyawan":
                        ubahDataJenisKaryawan();
                        break;
                    case "Jenis Barang":
                        ubahDataJenisBarang();
                        break;
                    case "Jenis Penjualan":
                        ubahDataJenisPenjualan();
                        break;
                    default:
                        break;
                }
            }
        }
    }//GEN-LAST:event_jTextAreaF1KeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (IdEdit == null) {
            switch (Title) {
                case "Jenis Karyawan":
                    GlobalVar.Var.tambahJenisKaryawan = null;
                    break;
                case "Jenis Barang":
                    GlobalVar.Var.tambahJenisBarang = null;
                    break;
                case "Jenis Penjualan":
                    GlobalVar.Var.tambahJenisPenjualan = null;
                    break;
                default:
                    break;
            }
        } else {
            switch (Title) {
                case "Jenis Karyawan":
                    GlobalVar.Var.ubahJenisKaryawan = null;
                    break;
                case "Jenis Barang":
                    GlobalVar.Var.ubahJenisBarang = null;
                    break;
                case "Jenis Penjualan":
                    GlobalVar.Var.ubahJenisPenjualan = null;
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMaster("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private KomponenGUI.JTextAreaF jTextAreaF1;
    private KomponenGUI.JbuttonF jbuttonF1;
    private KomponenGUI.JbuttonF jbuttonF2;
    private KomponenGUI.JbuttonF jbuttonF3;
    private KomponenGUI.JbuttonF jbuttonF4;
    private KomponenGUI.JlableF jlableF1;
    private KomponenGUI.JlableF jlableF3;
    private KomponenGUI.JlableF jlableF6;
    private KomponenGUI.JlableF jlableF8;
    private KomponenGUI.JtextF jtextF1;
    // End of variables declaration//GEN-END:variables

    void tambahDataJenisKaryawan(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = insert.simpan("INSERT INTO `tbsmjeniskaryawan`(`JenisKaryawan`, `Keterangan`) VALUES ('" + jtextF1.getText() + "','" + jTextAreaF1.getText() + "')", "Jenis Karyawan", this);
            if (berhasil) {
                if (tutup) {
                    dispose();
                } else {
                    jtextF1.setText("");
                    jTextAreaF1.setText("");
                    jtextF1.requestFocus();
                }
                if (GlobalVar.Var.listJenisKaryawan != null) {
                    GlobalVar.Var.listJenisKaryawan.refreshJenisKaryawan();
                }
            }
        }
    }

    void tambahDataJenisBarang(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = insert.simpan("INSERT INTO `tbsmjenisbarang`(`JenisBarang`, `Keterangan`) VALUES ('" + jtextF1.getText() + "','" + jTextAreaF1.getText() + "')", "Jenis Barang", this);
            if (berhasil) {
                if (tutup) {
                    dispose();
                } else {
                    jtextF1.setText("");
                    jTextAreaF1.setText("");
                    jtextF1.requestFocus();
                }
                if (GlobalVar.Var.listJenisBarang != null) {
                    GlobalVar.Var.listJenisBarang.refreshJenisBarang();
                }
            }
        }
    }

    void tambahDataJenisPenjualan(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = insert.simpan("INSERT INTO `tbsmjenispenjualan`(`JenisPenjualan`, `Keterangan`) VALUES ('" + jtextF1.getText() + "','" + jTextAreaF1.getText() + "')", "Jenis Penjualan", this);
            if (berhasil) {
                if (tutup) {
                    dispose();
                } else {
                    jtextF1.setText("");
                    jTextAreaF1.setText("");
                    jtextF1.requestFocus();
                }
                if (GlobalVar.Var.listJenisPenjualan != null) {
                    GlobalVar.Var.listJenisPenjualan.refreshJenisPenjualan();
                }
            }
        }
    }

    void ubahDataJenisKaryawan() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = update.Ubah("UPDATE `tbsmjeniskaryawan` SET `JenisKaryawan`='" + jtextF1.getText() + "',`Keterangan`='" + jTextAreaF1.getText() + "' WHERE `IdJenisKaryawan` = " + IdEdit, "Jenis Karyawan", this);
            if (berhasil) {
                dispose();
            }
            if (GlobalVar.Var.listJenisKaryawan != null) {
                GlobalVar.Var.listJenisKaryawan.refreshJenisKaryawan();
            }
        }
    }

    void ubahDataJenisBarang() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = update.Ubah("UPDATE `tbsmjenisbarang` SET `JenisBarang`='" + jtextF1.getText() + "',`Keterangan`='" + jTextAreaF1.getText() + "' WHERE `IdJenisBarang` = " + IdEdit, "Jenis Barang", this);
            if (berhasil) {
                dispose();
            }
            if (GlobalVar.Var.listJenisBarang != null) {
                GlobalVar.Var.listJenisBarang.refreshJenisBarang();
            }
        }
    }

    void ubahDataJenisPenjualan() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = update.Ubah("UPDATE `tbsmjenispenjualan` SET `JenisPenjualan`='" + jtextF1.getText() + "',`Keterangan`='" + jTextAreaF1.getText() + "' WHERE `IdJenisPenjualan` = " + IdEdit, "Jenis Penjualan", this);
            if (berhasil) {
                dispose();
            }
            if (GlobalVar.Var.listJenisPenjualan != null) {
                GlobalVar.Var.listJenisPenjualan.refreshJenisPenjualan();
            }
        }
    }

}
