/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import LSubProces.DRunSelctOne;
import LSubProces.Insert;
import LSubProces.Update;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author richky
 */
public class SubMaster extends javax.swing.JFrame {

    /**
     * Creates new form MasterKaryawan
     */
    String IdEdit, Title;

    public SubMaster(String title) {
        Title = title;
        initComponents();
        setVisible(true);
        setTitle("Sub Master " + Title);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        JBUbah.setVisible(false);
        JLNama.setText(Title);
    }

    public SubMaster(Object idEdit, String title) {
        IdEdit = idEdit.toString();
        Title = title;
        initComponents();
        setVisible(true);
        setTitle("Ubah Sub Master " + Title);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        JBTambah.setVisible(false);
        JBTambahTutup.setVisible(false);
        switch (Title) {
            case "Jenis Karyawan":
                loadeditdatajeniskaryawan();
                break;
            case "Jenis Barang":
                loadeditdatajenisbarang();
                break;
            case "Jenis Penjualan":
                loadeditdatajenispenjualan();
                break;
            default:
                break;
        }
        JLNama.setText(Title);
    }

    void loadeditdatajeniskaryawan() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdJenisKaryawan` as 'ID', `JenisKaryawan` as 'Jenis', `Keterangan` FROM `tbsmjeniskaryawan` WHERE `IdJenisKaryawan` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        JTNama.setText(list.get(1));
        JTKeterangan.setText(list.get(2));
    }

    void loadeditdatajenisbarang() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdJenisBarang` as 'ID', `JenisBarang` as 'Jenis', `Keterangan` FROM `tbsmjenisbarang` WHERE `IdJenisBarang` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        JTNama.setText(list.get(1));
        JTKeterangan.setText(list.get(2));
    }

    void loadeditdatajenispenjualan() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdJenisPenjualan` as 'ID', `JenisPenjualan` as 'Jenis', `Keterangan` FROM `tbsmjenispenjualan` WHERE `IdJenisPenjualan` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        JTNama.setText(list.get(1));
        JTKeterangan.setText(list.get(2));
    }

    Boolean checkInput() {
        if (JTNama.getText().replace(" ", "").equals("")) {
            JOptionPane.showMessageDialog(null, Title + " Tidak Boleh Kosong");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNama = new KomponenGUI.JlableF();
        JLNama2 = new KomponenGUI.JlableF();
        JTNama = new KomponenGUI.JtextF();
        JLKeterangan = new KomponenGUI.JlableF();
        JLKeterangan2 = new KomponenGUI.JlableF();
        JSPKeterangan = new javax.swing.JScrollPane();
        JTKeterangan = new KomponenGUI.JTextAreaF();
        JBTambah = new KomponenGUI.JbuttonF();
        JBTambahTutup = new KomponenGUI.JbuttonF();
        JBKembali = new KomponenGUI.JbuttonF();
        JBUbah = new KomponenGUI.JbuttonF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JLNama.setText("Nama Karyawan");

        JLNama2.setText(":");

        JTNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTNamaKeyPressed(evt);
            }
        });

        JLKeterangan.setText("Keterangan");

        JLKeterangan2.setText(":");

        JTKeterangan.setColumns(20);
        JTKeterangan.setRows(5);
        JTKeterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTKeteranganKeyPressed(evt);
            }
        });
        JSPKeterangan.setViewportView(JTKeterangan);

        JBTambah.setText("Tambah");
        JBTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTambahActionPerformed(evt);
            }
        });

        JBTambahTutup.setText("Tambah & Tutup");
        JBTambahTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTambahTutupActionPerformed(evt);
            }
        });

        JBKembali.setText("Kembali");
        JBKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKembaliActionPerformed(evt);
            }
        });

        JBUbah.setText("Ubah");
        JBUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTNama, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSPKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTambahTutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLKeterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JSPKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTambahTutup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTambahActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                tambahDataJenisKaryawan(false);
                break;
            case "Jenis Barang":
                tambahDataJenisBarang(false);
                break;
            case "Jenis Penjualan":
                tambahDataJenisPenjualan(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JBTambahActionPerformed

    private void JBTambahTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTambahTutupActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                tambahDataJenisKaryawan(true);
                break;
            case "Jenis Barang":
                tambahDataJenisBarang(true);
                break;
            case "Jenis Penjualan":
                tambahDataJenisPenjualan(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JBTambahTutupActionPerformed

    private void JBUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUbahActionPerformed
        switch (Title) {
            case "Jenis Karyawan":
                ubahDataJenisKaryawan();
                break;
            case "Jenis Barang":
                ubahDataJenisBarang();
                break;
            case "Jenis Penjualan":
                ubahDataJenisPenjualan();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_JBUbahActionPerformed

    private void JBKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_JBKembaliActionPerformed

    private void JTNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTKeterangan.requestFocus();
        }
    }//GEN-LAST:event_JTNamaKeyPressed

    private void JTKeteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTKeteranganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (IdEdit == null) {
                switch (Title) {
                    case "Jenis Karyawan":
                        tambahDataJenisKaryawan(false);
                        break;
                    case "Jenis Barang":
                        tambahDataJenisBarang(false);
                        break;
                    case "Jenis Penjualan":
                        tambahDataJenisPenjualan(false);
                        break;
                    default:
                        break;
                }
            } else {
                switch (Title) {
                    case "Jenis Karyawan":
                        ubahDataJenisKaryawan();
                        break;
                    case "Jenis Barang":
                        ubahDataJenisBarang();
                        break;
                    case "Jenis Penjualan":
                        ubahDataJenisPenjualan();
                        break;
                    default:
                        break;
                }
            }
        }
    }//GEN-LAST:event_JTKeteranganKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (IdEdit == null) {
            switch (Title) {
                case "Jenis Karyawan":
                    GlobalVar.Var.tambahJenisKaryawan = null;
                    break;
                case "Jenis Barang":
                    GlobalVar.Var.tambahJenisBarang = null;
                    break;
                case "Jenis Penjualan":
                    GlobalVar.Var.tambahJenisPenjualan = null;
                    break;
                default:
                    break;
            }
        } else {
            switch (Title) {
                case "Jenis Karyawan":
                    GlobalVar.Var.ubahJenisKaryawan = null;
                    break;
                case "Jenis Barang":
                    GlobalVar.Var.ubahJenisBarang = null;
                    break;
                case "Jenis Penjualan":
                    GlobalVar.Var.ubahJenisPenjualan = null;
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMaster("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private KomponenGUI.JbuttonF JBKembali;
    private KomponenGUI.JbuttonF JBTambah;
    private KomponenGUI.JbuttonF JBTambahTutup;
    private KomponenGUI.JbuttonF JBUbah;
    private KomponenGUI.JlableF JLKeterangan;
    private KomponenGUI.JlableF JLKeterangan2;
    private KomponenGUI.JlableF JLNama;
    private KomponenGUI.JlableF JLNama2;
    private javax.swing.JScrollPane JSPKeterangan;
    private KomponenGUI.JTextAreaF JTKeterangan;
    private KomponenGUI.JtextF JTNama;
    // End of variables declaration//GEN-END:variables

    void tambahDataJenisKaryawan(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = insert.simpan("INSERT INTO `tbsmjeniskaryawan`(`JenisKaryawan`, `Keterangan`) VALUES ('" + JTNama.getText() + "','" + JTKeterangan.getText() + "')", "Jenis Karyawan", this);
            if (berhasil) {
                if (tutup) {
                    dispose();
                } else {
                    JTNama.setText("");
                    JTKeterangan.setText("");
                    JTNama.requestFocus();
                }
                if (GlobalVar.Var.listJenisKaryawan != null) {
                    GlobalVar.Var.listJenisKaryawan.refreshJenisKaryawan();
                }
            }
        }
    }

    void tambahDataJenisBarang(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = insert.simpan("INSERT INTO `tbsmjenisbarang`(`JenisBarang`, `Keterangan`) VALUES ('" + JTNama.getText() + "','" + JTKeterangan.getText() + "')", "Jenis Barang", this);
            if (berhasil) {
                if (tutup) {
                    dispose();
                } else {
                    JTNama.setText("");
                    JTKeterangan.setText("");
                    JTNama.requestFocus();
                }
                if (GlobalVar.Var.listJenisBarang != null) {
                    GlobalVar.Var.listJenisBarang.refreshJenisBarang();
                }
            }
        }
    }

    void tambahDataJenisPenjualan(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = insert.simpan("INSERT INTO `tbsmjenispenjualan`(`JenisPenjualan`, `Keterangan`) VALUES ('" + JTNama.getText() + "','" + JTKeterangan.getText() + "')", "Jenis Penjualan", this);
            if (berhasil) {
                if (tutup) {
                    dispose();
                } else {
                    JTNama.setText("");
                    JTKeterangan.setText("");
                    JTNama.requestFocus();
                }
                if (GlobalVar.Var.listJenisPenjualan != null) {
                    GlobalVar.Var.listJenisPenjualan.refreshJenisPenjualan();
                }
            }
        }
    }

    void ubahDataJenisKaryawan() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = update.Ubah("UPDATE `tbsmjeniskaryawan` SET `JenisKaryawan`='" + JTNama.getText() + "',`Keterangan`='" + JTKeterangan.getText() + "' WHERE `IdJenisKaryawan` = " + IdEdit, "Jenis Karyawan", this);
            if (berhasil) {
                dispose();
            }
            if (GlobalVar.Var.listJenisKaryawan != null) {
                GlobalVar.Var.listJenisKaryawan.refreshJenisKaryawan();
            }
        }
    }

    void ubahDataJenisBarang() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = update.Ubah("UPDATE `tbsmjenisbarang` SET `JenisBarang`='" + JTNama.getText() + "',`Keterangan`='" + JTKeterangan.getText() + "' WHERE `IdJenisBarang` = " + IdEdit, "Jenis Barang", this);
            if (berhasil) {
                dispose();
            }
            if (GlobalVar.Var.listJenisBarang != null) {
                GlobalVar.Var.listJenisBarang.refreshJenisBarang();
            }
        }
    }

    void ubahDataJenisPenjualan() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = update.Ubah("UPDATE `tbsmjenispenjualan` SET `JenisPenjualan`='" + JTNama.getText() + "',`Keterangan`='" + JTKeterangan.getText() + "' WHERE `IdJenisPenjualan` = " + IdEdit, "Jenis Penjualan", this);
            if (berhasil) {
                dispose();
            }
            if (GlobalVar.Var.listJenisPenjualan != null) {
                GlobalVar.Var.listJenisPenjualan.refreshJenisPenjualan();
            }
        }
    }
}